# Generated by Django 2.2.5 on 2022-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ImgUrl',
            field=models.CharField(default='', max_length=500, verbose_name='图片url'),
        ),
    ]
