# Generated by Django 2.2.5 on 2022-03-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220321_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '女性'), (1, '男性')], default=0),
        ),
    ]
