# Generated by Django 2.2.5 on 2022-03-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='职位名称')),
                ('nature', models.CharField(max_length=255, verbose_name='招聘性质')),
                ('salary', models.CharField(max_length=20, verbose_name='薪资范围')),
                ('degree_required', models.CharField(max_length=255, verbose_name='学历要求')),
                ('location', models.CharField(max_length=255, verbose_name='工作地点')),
                ('number', models.CharField(max_length=255, verbose_name='招聘人数')),
                ('company', models.CharField(max_length=255, verbose_name='招聘公司')),
                ('request', models.CharField(max_length=255, verbose_name='专业要求')),
            ],
            options={
                'db_table': 'tb_jobs',
            },
        ),
    ]
