# Generated by Django 2.2.5 on 2022-03-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobinfo',
            table='workinfo_copy1',
        ),
    ]
